[Doc] Fix document link
open-mmlab/mmaction2 pull request #2457
Opened 2023-05-06 09:04 UTC by cir7

## Motivation
[Doc] Fix document link

2023-05-06 09:21 UTC, Dai-Wenxun approved these changes

2023-06-15 10:23 UTC, hukkai requested changes

2023-06-15 10:23 UTC, hukkai commented on README.md
> +[🛠️Installation](https://mmaction2.readthedocs.io/en/latest/get_started/installation/installation.html) |
this link is not right?

2023-06-15 10:23 UTC, hukkai commented on README.md
link not working

2023-06-15 10:23 UTC, hukkai commented on README.md
> +Please refer to [install.md](https://mmaction2.readthedocs.io/en/latest/get_started/installation/installation.html) for detailed instructions.
link not working

2023-06-15 10:23 UTC, hukkai commented on projects/README.md
> +- [Contribution Guide](https://mmaction2.readthedocs.io/en/latest/get_started/installation/contribution_guide.html)
link not working

2023-06-16 09:22 UTC, hukkai approved these changes

2023-06-16 09:31 UTC, merged