[Docs] Kinetics CN README
open-mmlab/mmaction2 pull request #731
Opened 2021-03-16 15:20 UTC by kennymckormick

2021-03-17 05:51 UTC, irvingzhang0512 commented on cn_docs/datatools/kinetics/README_cn.md
> +用户可以使用以下脚本准备视频，视频准备代码修改自[官方爬虫](https://github.com/activitynet/ActivityNet/tree/master/Crawler/Kinetics)。注意这一步骤将花费较长时间。
这个比较主观：从中文上看，准备视频、视频准备代码总感觉有一点点奇怪。
可以考虑用“获取/下载”代替“准备”

2021-03-17 05:51 UTC, irvingzhang0512 commented on cn_docs/datatools/kinetics/README_cn.md
> +**重要提示**：如果你在此之前已下载好 Kinetics 数据集的视频，你需要使用重命名脚本来替换掉类名中的空格：
删掉两个“你”字
如果在此之前已下载好 Kinetics 数据集的视频，需要使用重命名脚本来替换掉类名中的空格

2021-03-17 05:51 UTC, irvingzhang0512 commented on cn_docs/datatools/kinetics/README_cn.md
> +在完整完成 Kinetics 的数据处理后，你可以得到帧文件夹（RGB 帧和光流帧），视频以及标注文件。
你可以 -> 将

2021-03-17 05:51 UTC, irvingzhang0512 commented on cn_docs/datatools/kinetics/README_cn.md
> +你也可以从 [Academic Torrents](https://academictorrents.com/details/184d11318372f70018cf9a72ef867e2fb9ce1d26) 下载 Kinetics400 和 Kinetics700。
删除“你”

2021-03-17 05:53 UTC, congee524 commented
Pls move the file from `cn_docs/datatools/kinetics/README_cn.md` to `tools/data/kinetics/README_zh_CN.md`

2021-03-17 06:04 UTC, congee524 commented on cn_docs/datatools/kinetics/README_cn.md
> +在提取之前，请参考[安装教程](/docs_zh_CN/install_cn.md) 安装 [denseflow](https://github.com/open-mmlab/denseflow)。
`/docs_zh_CN/install_cn.md` -> `/docs_zh_CN/install.md`

2021-03-17 06:04 UTC, congee524 commented on cn_docs/datatools/kinetics/README_cn.md
> +更多细节可以参考[数据准备](/docs_zh_CN/data_preparation_cn.md)。
/docs_zh_CN/data_preparation.md

2021-03-17 06:04 UTC, congee524 commented on cn_docs/datatools/kinetics/README_cn.md
> +在完整完成 Kinetics 的数据处理后，你可以得到帧文件夹（RGB 帧和光流帧），视频以及标注文件。
在 ~~完整~~ 完成 Kinetics 的数据处理后

2021-03-17 06:04 UTC, congee524 commented on cn_docs/datatools/kinetics/README_cn.md
> +关于 Kinetics 数据集上的训练与测试，请参照[基础教程](/docs_zh_CN/getting_started_cn.md).
getting_started.md

2021-03-17 06:06 UTC, congee524 commented
You may need to rebase the latest `master` branch. **The file names of CN docs have changed** for the need of building Chinese readthedocs documents

2021-03-18 09:50 UTC, kennymckormick commented on cn_docs/datatools/kinetics/README_cn.md
> +用户可以使用以下脚本准备视频，视频准备代码修改自[官方爬虫](https://github.com/activitynet/ActivityNet/tree/master/Crawler/Kinetics)。注意这一步骤将花费较长时间。
命名为准备更加准确，由于同时涉及download & trim

2021-03-18 09:52 UTC, kennymckormick commented on cn_docs/datatools/kinetics/README_cn.md
> +在完整完成 Kinetics 的数据处理后，你可以得到帧文件夹（RGB 帧和光流帧），视频以及标注文件。
此处完整表示也进行了抽帧操作, which is optional

2021-03-18 09:55 UTC, kennymckormick commented
All conversations under this PR are resolved. To avoid the troubles of rebasing, I will close this PR and reopen a new one.

2021-03-22 02:40 UTC, congee524 commented on tools/data/kinetics/README_zh_CN.md
> +如果用户有足够的 SSD 空间，那么建议将视频抽取为 RGB 帧以提升 I/O 性能。用户可以使用以下脚本为抽取得到的帧文件夹建立软连接：
建立软链接

2021-03-22 02:40 UTC, congee524 requested changes
和 #733 #742 统一风格

2021-03-24 02:58 UTC, innerlee approved these changes

2021-03-24 03:00 UTC, innerlee commented
@congee524 let's do the polish pass in a following pr

2021-03-24 03:02 UTC, merged