sub CN data preparation
open-mmlab/mmaction2 pull request #733
Opened 2021-03-17 07:19 UTC by dreamerlin

- [x] ucf101
- [x] sthv1
- [x] sthv2
- [x] ucf101_24
- [ ] jhmdb
- [ ] ANet

2021-03-18 02:51 UTC, innerlee commented on tools/data/activitynet/README_zh-CN.md
> +对于时序动作检测任务，用户可以使用这个 [代码库](https://github.com/wzmsltw/BSN-boundary-sensitive-network#code-and-data-preparation) 提供的经缩放（rescaled）的 ActivityNet 特征，
经缩放 -> 缩放过

2021-03-18 02:53 UTC, innerlee commented on tools/data/activitynet/README_zh-CN.md
> +首先，用户可以使用以下命令进行标注文件下载。
> 进行标注文件下载
下载标注文件

2021-03-18 02:53 UTC, innerlee commented on tools/data/activitynet/README_zh-CN.md
> +之后，用户可以使用以下命令进行 activitynet 特征下载。
~~用户~~可以使用

2021-03-18 02:54 UTC, innerlee commented on tools/data/activitynet/README_zh-CN.md
> +之后，用户可以使用以下命令进行 activitynet 特征下载。
下载 activitynet 特征

2021-03-18 02:58 UTC, innerlee commented on tools/data/activitynet/README_zh-CN.md
> +首先，用户可以使用以下命令进行标注文件下载。
下载xxx

2021-03-18 02:58 UTC, innerlee commented on tools/data/activitynet/README_zh-CN.md
> +之后，用户可以使用以下脚本进行视频数据的准备
准备xxx

2021-03-18 03:00 UTC, innerlee commented on tools/data/jhmdb/README_zh-CN.md
> +用户可以从 [这里](https://drive.google.com/drive/folders/1BvGywlAGrACEqRyfYbz3wzlVV3cDFkct) 下载 RGB 帧，光流和基准标注文件。
基准标注文件 ?

2021-03-18 03:23 UTC, dreamerlin commented on tools/data/jhmdb/README_zh-CN.md
> +用户可以从 [这里](https://drive.google.com/drive/folders/1BvGywlAGrACEqRyfYbz3wzlVV3cDFkct) 下载 RGB 帧，光流和基准标注文件。
ground truth annotations

2021-03-18 04:02 UTC, innerlee commented on tools/data/jhmdb/README_zh-CN.md
> +用户可以从 [这里](https://drive.google.com/drive/folders/1BvGywlAGrACEqRyfYbz3wzlVV3cDFkct) 下载 RGB 帧，光流和基准标注文件。
直接用标注文件吧

2021-03-18 04:03 UTC, innerlee commented on tools/data/jhmdb/README_zh-CN.md
> +用户可以从 [这里](https://drive.google.com/drive/folders/1BvGywlAGrACEqRyfYbz3wzlVV3cDFkct) 下载 RGB 帧，光流和基准标注文件。
ground truth 译基准不太好

2021-03-18 04:04 UTC, innerlee commented on tools/data/jhmdb/README_zh-CN.md
> +1. `labels` (list)：21 个标签组成的 list
list 列表
dict 字典

2021-03-18 04:05 UTC, innerlee commented on tools/data/sthv1/README_zh-CN.md
> +如果用户只想使用原 RGB 帧进行加载训练，则该部分是 **可选项**。
~~进行~~

2021-03-18 04:06 UTC, innerlee commented on tools/data/sthv1/README_zh-CN.md
> +在抽取视频帧和光流之前，请参考 [安装指南](/docs_zh_CN/install.md) 进行 [denseflow](https://github.com/open-mmlab/denseflow) 的安装。
安装xx

2021-03-18 04:06 UTC, innerlee commented on tools/data/sthv1/README_zh-CN.md
> +如果用户有大量的 SSD 存储空间，则推荐将抽取的帧存储至 I/O 性能更优秀的 SSD 存储中。
~~用户~~

2021-03-18 04:06 UTC, innerlee commented on tools/data/sthv1/README_zh-CN.md
> +用户可以运行以下命令在 SSD 中建立软连接。
~~用户~~

2021-03-18 04:06 UTC, innerlee commented on tools/data/sthv1/README_zh-CN.md
> +如果用户想抽取光流，则可以运行以下脚本从 RGB 帧中抽取出光流。
~~用户~~

2021-03-18 04:35 UTC, congee524 commented on tools/data/jhmdb/README_zh-CN.md
> +用户可以从 [这里](https://drive.google.com/drive/folders/1BvGywlAGrACEqRyfYbz3wzlVV3cDFkct) 下载 RGB 帧，光流和基准标注文件。
真实标签？

2021-03-18 06:08 UTC, dreamerlin commented on tools/data/jhmdb/README_zh-CN.md
> +用户可以从 [这里](https://drive.google.com/drive/folders/1BvGywlAGrACEqRyfYbz3wzlVV3cDFkct) 下载 RGB 帧，光流和基准标注文件。
真实标签？@innerlee

2021-03-18 14:32 UTC, irvingzhang0512 reviewed
由于文档内容大量重复，部分修改意见适用于其他文档。如果采纳我的建议，希望全局搜索一下，修改其他相同之处。我就不一一列举出来了。

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/activitynet/README_zh-CN.md
> +You need to use Kinetics models for pretraining.
英文忘删了？

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/activitynet/README_zh-CN.md
> +用户可使用 `configs/recognition/tsn` 目录下的 ActivityNet 的配置文件进行 TSN 模型微调。
下的 -> 中

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/activitynet/README_zh-CN.md
> +用户需要使用 Kinetics 相关模型进行预训练，并且同时支持 RGB 模型和光流模型。
用户需要使用 Kinetics 相关模型（同时支持 RGB 模型与光流模型）进行预训练。

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/activitynet/README_zh-CN.md
> +在走完完整的 ActivityNet 数据集准备流程后，
在走完完整的 -> 在完成所有/在完成
另外，本行和下一行放一行应该没问题吧

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/jhmdb/README_zh-CN.md
> +在数据集准备前，请确保当前所在文件夹位置为 `$MMACTION2/tools/data/jhmdb//`。
多了一个斜杠
另外，对这个`请确保当前所在文件夹位置为`其实我觉得翻译得不准确，或者说不明确。可能翻译成“命令行当前路径”一类的更好一些

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/jhmdb/README_zh-CN.md
> +参考自 [act-detector](https://github.com/vkalogeiton/caffe/tree/act-detector)。
MOC 和 act-detector 需要分两行吗？如果从中文看，以逗号结尾，字数很少，好像不太对。

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/jhmdb/README_zh-CN.md
> +如果拥有大量的 SSD 存储空间，则推荐将抽取的帧存储至 I/O 性能更优秀的 SSD 存储中。
则推荐将抽取的帧存储至 I/O 性能更优秀的 SSD ~存储~中
出现不止一处

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/jhmdb/README_zh-CN.md
> +可以运行以下命令在 SSD 中建立软连接。
这句翻译有问题，不是“在SSD中建立”，“为SSD建立”

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/jhmdb/README_zh-CN.md
> +1. `labels` (list)：21 个标签组成的列表
虽然英文是label，但不建议翻译成标签，容易混淆。这里指的是**行为类别名称**，而不是我们一般说的ground truth label。

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/sthv1/README_zh-CN.md
> +首先，用户需要在 [官网](https://20bn.com/datasets/something-something/v1) 进行注册，才能对标注文件进行下载。下载好的标准文件需要放在 `$MMACTION2/data/sthv1/annotations` 文件夹下。
才能对标注文件进行下载 -> 才能下载标注文件
标准文件 -> 标注文件

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/sthv1/README_zh-CN.md
> +因为 [官网](https://20bn.com/datasets/something-something/v1) 并未提供原始视频文件，只提供了对原视频文件进行抽取得到的 RGB 帧，用户可在 [官网](https://20bn.com/datasets/something-something/v1) 直接对其进行下载。
感觉没有因果关系，建议删除 `因为`
直接对其进行下载 -> 直接下载

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/sthv1/README_zh-CN.md
> +将下载好的 RGB 帧放在 `$MMACTION2/data/sthv1/` 文件夹下，并使用以下脚本进行解压。
下载好的不是 RGB 帧吧，而是 20bn-something-something-v1-?? 这种形式的，可能叫“压缩文件”比较合适？

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/sthv1/README_zh-CN.md
> +如果用户只想使用原 RGB 帧加载训练，则该部分是 **可选项**。
删除 原

2021-03-18 14:32 UTC, irvingzhang0512 commented on tools/data/sthv2/README_zh-CN.md
> +之后，用户可将下载好的视频放在 `$MMACTION2/data/sthv2/` 文件夹下，并且使用以下指令进行解压。
下载好的不是视频，而是压缩文件

2021-03-18 16:21 UTC, dreamerlin commented on tools/data/jhmdb/README_zh-CN.md
> +参考自 [act-detector](https://github.com/vkalogeiton/caffe/tree/act-detector)。
MOC 的数据是参考 act-detector 的，这个经过原作者确认过

2021-03-18 16:23 UTC, irvingzhang0512 commented on tools/data/jhmdb/README_zh-CN.md
> +参考自 [act-detector](https://github.com/vkalogeiton/caffe/tree/act-detector)。
呃，我没说清楚。我的意思是，在文档里，从文字角度看，应该一行就可以了……

该数据由 [MOC](https://github.com/MCG-NJU/MOC-Detector/blob/master/readme/Dataset.md) 代码库提供，参考自 [act-detector](https://github.com/vkalogeiton/caffe/tree/act-detector)。

2021-03-19 00:56 UTC, irvingzhang0512 commented on tools/data/jhmdb/README_zh-CN.md
> +用户可以从 [这里](https://drive.google.com/drive/folders/1BvGywlAGrACEqRyfYbz3wzlVV3cDFkct) 下载 RGB 帧，光流和基准标注文件。
个人感觉，不用突出“真实”，在我们的场景下，也没有“假标签”的概念。不如直接用标注文件。

2021-03-19 03:37 UTC, congee524 commented on tools/data/jhmdb/README_zh-CN.md
> +在数据集准备前，请确保当前所在文件夹位置为 `$MMACTION2/tools/data/jhmdb//`。
请确保当前工作目录为

2021-03-19 03:39 UTC, congee524 commented on tools/data/activitynet/README_zh-CN.md
> +或者使用 MMAction2 进行特征提取（这将具有更好地精度）。MMAction2 同时提供了以上所述的两种数据使用流程。
这将具有更高的精度

2021-03-19 03:39 UTC, congee524 commented on tools/data/activitynet/README_zh-CN.md
> +在数据集准备前，请确保命令行当前路径为 `$MMACTION2/tools/data/activitynet/`。
请确保当前工作目录为

2021-03-19 03:55 UTC, congee524 commented on tools/data/activitynet/README_zh-CN.md
> +或者使用 MMAction2 进行特征提取（这将具有更好地精度）。MMAction2 同时提供了以上所述的两种数据使用流程。
这将具有更高的精度

2021-03-19 03:55 UTC, congee524 commented on tools/data/jhmdb/README_zh-CN.md
> +如果拥有大量的 SSD 存储空间，则推荐将抽取的帧存储至 I/O 性能更优秀的 SSD 中。
SSD 可以都翻译为 固态硬盘

2021-03-19 03:55 UTC, congee524 commented on tools/data/sthv1/README_zh-CN.md
> +由于官网的 JPG 文件名形如 "%05d.jpg" （比如，"00001.jpg"），需要在配置文件的 `data.train`, `data.val` 和 `data.test` 处添加 "filename_tmpl='{:05}.jpg'" 代码，以修改文件名模板。
"filename_tmpl='{:05}.jpg'" 旁边加上代码引用符号 `

2021-03-19 03:55 UTC, congee524 commented on tools/data/sthv2/README_zh-CN.md
> +在数据集准备前，请确保命令行当前路径为 `$MMACTION2/tools/data/sthv2/`。
当前工作目录

2021-03-19 03:55 UTC, congee524 commented on tools/data/ucf101_24/README_zh-CN.md
> +在数据集准备前，请确保命令行当前路径为 `$MMACTION2/tools/data/ucf101_24/`。
当前工作目录

2021-03-19 03:55 UTC, congee524 commented on tools/data/ucf101_24/README_zh-CN.md
> +用户可以从 [这里](https://drive.google.com/drive/folders/1BvGywlAGrACEqRyfYbz3wzlVV3cDFkct) 下载 RGB 帧，光流和基准标注文件。
这个基准标注文件，我赞同全部改成`标注文件`

2021-03-19 03:55 UTC, congee524 commented on tools/data/jhmdb/README_zh-CN.md
> +用户可以从 [这里](https://drive.google.com/drive/folders/1BvGywlAGrACEqRyfYbz3wzlVV3cDFkct) 下载 RGB 帧，光流和基准标注文件。
赞同标注文件

2021-03-19 04:27 UTC, congee524 commented on tools/data/sthv2/README_zh-CN.md
> +可以运行以下命令为 SSD 建立软连接。
建立软链接

2021-03-19 04:35 UTC, irvingzhang0512 commented on tools/data/activitynet/README_zh-CN.md
> +在数据集准备前，请确保命令行当前路径为 `$MMACTION2/tools/data/activitynet/`。
**命令行当前路径** 是我提的意见。
主要原因在于 **当前工作目录** 不明确，新用户一开始很难理解这个词的准确含义，可能不会联想到**命令行**，不如直接写明是 **命令行**的当前路径，减少歧义

2021-03-19 04:38 UTC, congee524 commented on tools/data/sthv2/README_zh-CN.md
> +## 步骤 1. 准备标注文件
下载标注文件

2021-03-19 04:38 UTC, congee524 commented on tools/data/sthv2/README_zh-CN.md
> +## 步骤 2. 准备视频
下载视频

2021-03-19 04:40 UTC, congee524 commented on tools/data/activitynet/README_zh-CN.md
> +在数据集准备前，请确保命令行当前路径为 `$MMACTION2/tools/data/activitynet/`。
这个词个人感觉含义是很准确的，是专用术语，在操作系统等相关课程上教过。维基百科也有相关词条，https://zh.wikipedia.org/wiki/%E5%B7%A5%E4%BD%9C%E7%9B%AE%E9%8C%84

2021-03-19 04:54 UTC, irvingzhang0512 commented on tools/data/activitynet/README_zh-CN.md
> +在数据集准备前，请确保命令行当前路径为 `$MMACTION2/tools/data/activitynet/`。
可改成 **命令行工作目录**
工作目录本身作为专有名词没有问题，如果已经确定了语境（比如在操作系统课程、或者就在讨论Linux系统），的确非常准确。但在日常交流中，提到 **工作目录** 要直接想到是 Linux 系统、命令行，那就可能会有一些问题。

刚刚询问了4位同事，1位运维以及1位算法同事表示很好理解，另外2位算法工程师觉得有点模糊（理由是，一般都是看英文，中文的这个专有名词没看到过），供参考

2021-03-19 05:02 UTC, congee524 commented on tools/data/activitynet/README_zh-CN.md
> +在数据集准备前，请确保命令行当前路径为 `$MMACTION2/tools/data/activitynet/`。
我个人会觉得 `命令行工作目录` 有些别扭
@innerlee @dreamerlin @kennymckormick 你们的想法呢？

2021-03-19 05:11 UTC, kennymckormick commented on tools/data/activitynet/README_zh-CN.md
> +在数据集准备前，请确保命令行当前路径为 `$MMACTION2/tools/data/activitynet/`。
我认为 命令行当前路径 或 当前路径 即可，由于用户仅可能在命令行下执行脚本

2021-03-19 05:23 UTC, congee524 commented on tools/data/activitynet/README_zh-CN.md
> +在数据集准备前，请确保命令行当前路径为 `$MMACTION2/tools/data/activitynet/`。
好的，那我也在我那部分统一风格。

2021-03-19 05:25 UTC, congee524 commented on tools/data/sthv1/README_zh-CN.md
> +可以运行以下命令为 SSD 建立软连接。
软链接

2021-03-19 08:31 UTC, congee524 commented on tools/data/sthv1/README_zh-CN.md
> +如果用户只想使用 RGB 帧，则可以跳过中间步骤至步骤 5 以直接生成视频帧的标注文件。
标注文件 -> 文件列表

2021-03-19 10:19 UTC, dreamerlin commented on tools/data/jhmdb/README_zh-CN.md
> +如果拥有大量的 SSD 存储空间，则推荐将抽取的帧存储至 I/O 性能更优秀的 SSD 中。
I think SSD is OK

2021-03-22 02:17 UTC, congee524 approved these changes
You may need to polish the document according to #742

2021-03-22 02:18 UTC, congee524 requested changes
You may need to polish the document according to #742

2021-03-22 06:42 UTC, dreamerlin commented
Done

2021-03-22 06:55 UTC, congee524 approved these changes

2021-03-24 02:58 UTC, merged