[Docs] HVU CN README
open-mmlab/mmaction2 pull request #738
Opened 2021-03-18 12:25 UTC by kennymckormick

2021-03-22 02:35 UTC, congee524 commented on tools/data/hvu/README_zh_CN.md
> +该脚本默认生成短边长度为 256 的帧，可参考 [数据准备](/docs_zh_CN/data_preparation.md) 获得更多细节。
长度为 256 像素

2021-03-22 02:36 UTC, congee524 requested changes
意见和 #739 一样，和 #733 #742 统一风格

2021-03-24 02:29 UTC, innerlee approved these changes

2021-03-24 03:03 UTC, innerlee commented
@congee524 let's do the polish pass in a following pr

2021-03-24 03:03 UTC, merged