[Docs] GYM CN README
open-mmlab/mmaction2 pull request #739
Opened 2021-03-18 12:40 UTC by kennymckormick

2021-03-22 02:34 UTC, congee524 commented on tools/data/gym/README_zh_CN.md
> +在开始之前，用户需确保当前目录为 `$MMACTION2/tools/data/gym/`。
命令行当前路径

2021-03-22 02:34 UTC, congee524 commented on tools/data/gym/README_zh_CN.md
> +## 2. 准备视频
下载视频

2021-03-22 02:34 UTC, congee524 commented on tools/data/gym/README_zh_CN.md
> +用户可以使用以下脚本准备视频，视频准备代码修改自 [ActivityNet 爬虫](https://github.com/activitynet/ActivityNet/tree/master/Crawler/Kinetics)。
准备 -> 下载

2021-03-22 02:34 UTC, congee524 commented on tools/data/gym/README_zh_CN.md
> +```
也许需要和其他PR #733 #742 保持一致

2021-03-22 02:34 UTC, congee524 commented on tools/data/gym/README_zh_CN.md
> +在整个项目目录下（仅针对 GYM），完整目录结构如下所示：
也许需要和其他PR #733 #742 保持一致

2021-03-22 02:34 UTC, congee524 requested changes
最好调整翻译和 #733 和 #742 保持一致

2021-03-24 02:55 UTC, innerlee approved these changes

2021-03-24 03:04 UTC, innerlee commented
@congee524 let's do the polish pass in a following pr

2021-03-24 03:04 UTC, merged